### ISSUE TITLE
How can the new `CMD Move` command be used mentioned in updated Wiki

### ISSUE THREAD

**Issue by grigals** [CommonplaceRobotics/CRI-DemoClient#3]
How can the new `CMD Move` command be used mentioned in updated Wiki

It is mentioned in this link, but PDF document does not show how to use it.
https://wiki.cpr-robots.com/index.php/Moving_Robots_via_CRI

**Comment by cpr-mab** [comment]
The CRI documentation PDF is not updated yet since version 12 of TinyCtrl/CPRog/iRC is not officially released.

If you received a robot with version 12 or if you updated to the pre release (https://wiki.cpr-robots.com/index.php/IgusRobotControl-DE-Release12Pre) you can use the CMD Move command as follows:

> CRISTART 1234 CMD Move [Type] 0 0 0 0 0 0 0 0 0 [velocity] CRIEND
Starts a motion to a specific position. The parameters depend on type:
Joint or RelativeJoint: 6 robot joint values, 3 external joint values.
Cart, RelativeBase, RelativeTool: 3 cartesian position values, 3 orientation values (currently not used), 3 external joint values.
In case of joint motion the last value is velocity in percent of maximum velocity (1-100). In case of cartesian the motion velocity is in mm/s.
If this command is sent while an earlier motion is not finished yet the previous motion will be stopped and replaced by the new one. Robot Program execution has higher precedence than this command while this command has higher precedence than jog motion.
When the target position is reached or if an error occurred the same messages will be sent as during robot program execution.

> CRISTART 1234 CMD Move Stop CRIEND
Stops a CMD Move motion.
